version: '3'
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'gagandeepsingh'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGO_USERNAME: gagan
      MONGO_PASSWORD: '123456'
      MONGO_URI: localhost
      AUTH_API_ADDRESS: 'auth:3000'
  tasks:
    build: ./tasks-api
    ports:
      - '3000:3000'
    environment:
      MONGO_USERNAME: gagan
      MONGO_PASSWORD: '123456'
      MONGO_URI: localhost
      AUTH_API_ADDRESS: 'auth:3000'
