apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: gagandeep39/k8s-node-eks-auth-api:latest
          env:
            - name: TOKEN_KEY
              value: 'gagandeepsingh'
          resources:
            limits:
              memory: '128Mi'
              cpu: '150m'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
