apiVersion: v1
kind: Pod
metadata:
  name: mongo-depl
  labels:
    name: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      resources:
        limits:
          memory: '128Mi'
          cpu: '150m'
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: gagan
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: '123456'
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
